# Generated by Django 4.2 on 2025-04-23 06:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skin_tone', models.CharField(blank=True, choices=[('fair', 'Fair'), ('light', 'Light'), ('medium', 'Medium'), ('olive', 'Olive'), ('tan', 'Tan'), ('deep', 'Deep')], max_length=20)),
                ('height', models.IntegerField(blank=True, help_text='Height in cm', null=True)),
                ('body_type', models.CharField(blank=True, choices=[('rectangle', 'Rectangle'), ('triangle', 'Triangle'), ('inverted_triangle', 'Inverted Triangle'), ('hourglass', 'Hourglass'), ('apple', 'Apple')], max_length=20)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('casual', 'Casual'), ('formal', 'Formal'), ('business', 'Business'), ('party', 'Party'), ('date', 'Date'), ('outdoor', 'Outdoor')], max_length=20)),
                ('climate', models.CharField(choices=[('hot', 'Hot'), ('warm', 'Warm'), ('mild', 'Mild'), ('cool', 'Cool'), ('cold', 'Cold'), ('rainy', 'Rainy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('is_favorite', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('footwear', 'Footwear'), ('accessory', 'Accessory')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='outfit_items/')),
                ('shopping_link', models.URLField(blank=True, null=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='stylist.outfitsuggestion')),
            ],
        ),
    ]
